---
- name: Test firmware is at a specific version
  hosts: plc
  gather_facts: false
  tasks:
  - name: Ensure firmware is at a specific version
    community.cip.ensure_firmware_version:
      revision: "{{ hostvars[inventory_hostname]['revision'] }}"
    register: ensure_firmware_version_out

  - name: Debug
    ansible.builtin.debug:
      var: ensure_firmware_version_out
